---
- name: Install WordPress, MySQL, Nginx, and PHP-FPM
 hosts:127.0.0.1 
#  remote_user: root
  # remote_user: user
  # sudo: yes

  roles:
    - common
    - mysql
    - nginx
    - php-fpm
    - wordpress
